Testsuite: C++11 compatibility (GCC's -Wliteral-suffix).
With "g++ -Werror", several .c files in the "tests" directory were
yielding

  error: invalid suffix on literal; C++11 requires a space between
  literal and string macro [-Werror=literal-suffix]

(cherry picked from commit 1abc323e3caea0e59b010152c2b9507bc045311b)